### ISSUE TITLE
Could not find apk file at path './platforms/android/build/outputs/apk/android-release.apk'

### ISSUE THREAD

**Issue by muhzi4u** [bamlab/fastlane-plugin-cordova#1]
I am using [crosswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview)  plugin in my ionic project.So there will two types of android builds [X86 and ARM].How can i take this two release builds for beta release.Thanks
![screen shot 2017-04-29 at 3 11 38 pm](https://cloud.githubusercontent.com/assets/12408980/25554584/4f682934-2cee-11e7-9760-eced5da16293.png)

**Comment by SimeonC** [comment]
I'm using cordova (which looks like it outputs the same structure) and I think the problem is your apk file path. I use: `apk_path: 'platforms/android/build/outputs/apk/android-release.apk'` and it works, but didn't when I had the same path you do.

**Comment by muhzi4u** [comment]
I am using crosswalk in my ionic project.So there will be two build files [ARM or X86]

1.android-armv7-release.apk [platforms/android/build/outputs/apk/android-armv7-release.apk]
2.android-x86-release.apk [platforms/android/build/outputs/apk/android-x86-release.apk ]

I need to upload both files

**Comment by SimeonC** [comment]
OK. I think your problem here isn't the cordova plugin - If you look at the end it says both of the apks are created. In your `Fastfile` you'll have a supply section. From the supply help `fastlane supply --help` you get this option `-u, --apk_paths ARRAY An array of paths to APK files to upload (SUPPLY_APK_PATHS)`.

So I think if you change the supply params from (I think you have currently):
```
supply(
  ...
  apk: './platforms/android/build/outputs/apk/android-armv7-release.apk'
  ...
)
```
To this:
```
supply(
  ...
  apk_paths: ['platforms/android/build/outputs/apk/android-armv7-release.apk', 'platforms/android/build/outputs/apk/android-x86-release.apk']
  ...
)
```
You should at least be getting a few more steps closer.

**Comment by SimeonC** [comment]
I'm pretty new to this as well, I found this code in the repo which is what you're talking about.
```ruby
def self.set_build_paths()
  app_name = self.get_app_name()

  ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'] = "./platforms/android/build/outputs/apk/android-release.apk"
  ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'] = "./platforms/ios/build/device/#{app_name}.ipa"
end
```
So all they've done is hard code the paths, as fastlane is just in ruby you could do your own script to grab the list of apks dynamically as only the apks should be in that folder. Or just hardcode the two filenames you need.

**Comment by muhzi4u** [comment]
@SimeonC Thanks your support.It is working now.
 **Fastlane**
```
platform :android do
  desc "Submit a new Beta Build"
  lane :beta do
    #gradle(task: "assembleRelease")
     cordova(
      platform: 'android',
      keystore_path: './config/****.keystore',
      keystore_alias: '*****',
      keystore_password: '******',
      team_id:'*****'
    )
    # Cordova Fastlane Plugin
    supply(
       track:'beta',
       apk_paths: [
       'platforms/android/build/outputs/apk/android-armv7-release.apk', 
       'platforms/android/build/outputs/apk/android-x86-release.apk'
       ]
       
    )
  end
end
```

**Comment by Almouro** [comment]
Thanks @muhzi4u and @SimeonC for helping out with this!
Wow, I did not even have anything to do for this issue, you guys are awesome! 👍 

I am adding a line in the README.md about using Crosswalk in case someone else encounters the problem :)

**Comment by muhzi4u** [comment]
@Almouro Glad to help you.I have uploaded ios beta version also.
fastlane
```
platform :ios do
  desc "Deploy ios app on the appstore"
  lane :beta do
    cert
    sigh
    gym(
       scheme: "APP_SCHEMA_NAME"
    )
    testflight
    cordova(platform: 'ios') 
    appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end

```

**Comment by sergii-frost** [comment]
Hi, 

I know that this issue is closed, but it seems I am getting similar one.
This can be due to using latest gradle and ionic/cordova.

Gradle: 4.5
`ionic info`

```
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-sim           : 6.1.2
    Node              : v9.4.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Applications/android-sdk

Misc:

    backend : pro
```

When having fastlane lane like:

```
  desc "Build Release apk"
  desc "Upload to HockeyApp"
  lane :build_release_hockeyapp do
    cordova(
      platform: 'android',
      cordova_prepare: true,
      release: true,
      device: true,
      build_number: number_of_commits,
     //keystore setup following
    )
    print(ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
```

Output of this lane is:

```
[17:33:49]: ▸ 47 actionable tasks: 12 executed, 35 up-to-date
[17:33:49]: ▸ Built the following apk(s):
[17:33:49]: ▸ /Users/.../app/platforms/android/app/build/outputs/apk/release/app-release.apk
...
./platforms/android/build/outputs/apk/android-release.apk
```

As you can see, echo from cordova points to correct path which is `/platforms/android/app/build/outputs/apk/release/app-release.apk` while `ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH']` is missing `app` after `./platforms/android`

**Comment by gmarineau** [comment]
Hi,

I have the same issue than @sergii-frost did you find a solution ? Like you my APK is save in the app folder.

 I get each time this message from fastlane: 

`[14:51:40]: Error setting value '../platforms/android/app/build/outputs/apk/app-release.apk' for option 'apk'
[14:51:40]: You passed invalid parameters to 'supply'.
[14:51:40]: Check out the error below and available options by running `fastlane action supply`
[14:51:40]: Sending crash report...
[14:51:40]: The stack trace is sanitized so no personal information is sent.
[14:51:40]: To see what we are sending, look here: /home/circleci/.fastlane/latest_crash.json
[14:51:40]: Learn more at https://docs.fastlane.tools/actions/opt_out_crash_reporting/
[14:51:40]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile`

**Comment by gmarineau** [comment]
@sergii-frost okok I have make the same thing.
