### ISSUE TITLE
--debug or --release?

### ISSUE THREAD

**Issue by janpio** [bamlab/fastlane-plugin-cordova#16]
Does this plugin support supplying `--debug` or `--release` to `cordova build`?

**Comment by janpio** [comment]
Hmmm yes, looks like it does:

https://github.com/bamlab/fastlane-plugin-cordova/blob/master/lib/fastlane/plugin/cordova/actions/cordova_action.rb#L72

Just no documentation in README :/

**Comment by janpio** [comment]
https://github.com/bamlab/fastlane-plugin-cordova/blob/master/lib/fastlane/plugin/cordova/actions/cordova_action.rb#L134-L142 indicates it is a boolean, so porbably

```
cordova(release: false)
```
for debug? `--release` seems to be default.

**Comment by Almouro** [comment]
Hi @janpio,

Thanks for posting an issue!

Indeed, with the [logic here](https://github.com/bamlab/fastlane-plugin-cordova/blob/master/lib/fastlane/plugin/cordova/actions/cordova_action.rb#L72), 
```
cordova(release: false)
```
will indeed run cordova debug.

I can update the docs to make that clear :)

**Comment by janpio** [comment]
That would be great. (Same for the other undocumented options if you have the time.)

**Comment by Almouro** [comment]
@janpio how's [this](https://github.com/bamlab/fastlane-plugin-cordova#plugin-api) then? :)

**Comment by janpio** [comment]
You had that prepared, didn't you?

Nice! Thanks.

**Comment by Almouro** [comment]
@janpio ha no, the command `fastlane actions cordova` was already returning these info, so I just copy pasted it and formatted it for markdown

**Comment by janpio** [comment]
Oh. I didn't get that far ;)
