### ISSUE TITLE
Xcode 9?

### ISSUE THREAD

**Issue by janpio** [bamlab/fastlane-plugin-cordova#17]
Anyone using this plugin with Xcode 9 already and having success building iOS projects with certificates and all?

**Comment by Almouro** [comment]
Hi @janpio, works for me!
not much has changed actually in terms of signing (compared to XCode 8 vs 7).
Are you having an issue? :)

**Comment by janpio** [comment]
Yep, but was caused by a new Cordova project with the the original Xcode project format. 
I'm just creating https://github.com/ionic-zone/fastlane-plugin-upgrade_super_old_xcode to have an automated way to fix the problem.
