### ISSUE TITLE
Add support for buildFlag iOS args

### ISSUE THREAD

**Issue by blackholegalaxy** [bamlab/fastlane-plugin-cordova#37]
@Almouro Hi there!

Do you think it's possible to add support, on ios args, for `buildFlag`. Indeed it can be useful to push buildFlag to cordova compile command sometimes.

for example:

`cordova compile ios --buildFlag='-UseModernBuildSystem=0'`

buildFlag can be multiple and have then to be written:

`cordova compile ios --buildFlag='-UseModernBuildSystem=0' --buildFlag='-anotherFlag=value'`

PR opened, needs review:

https://github.com/bamlab/fastlane-plugin-cordova/pull/38

**Comment by jpgilchrist** [comment]
I think this is pretty critical given the release of xcode10... see related issues with cordova here: https://github.com/apache/cordova-ios/issues/412

**Comment by blackholegalaxy** [comment]
PR opened, review welcome as Ruby is not quite my everyday business
