### ISSUE TITLE
cordova-iOS 7 broken build path

### ISSUE THREAD

**Issue by nicholaszuccarelli** [bamlab/fastlane-plugin-cordova#62]
ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'] = "./platforms/ios/build/device/#{app_name}.ipa"

Cordova-iOS 7.0 has changed the build path
https://cordova.apache.org/announcements/2023/07/10/cordova-ios-7.0.0.html

instead of /device/, it is now /Build-iphoneos/

**Comment by tylervz** [comment]
This is where that line of code resides if anyone would like to create a pull request:
https://github.com/bamlab/fastlane-plugin-cordova/blob/981dceaea67b591022fe210eb958a48a9b64a73d/lib/fastlane/plugin/cordova/actions/cordova_action.rb#L129
